name: elte_calendar
description: "University calendar application for ELTE students to import and manage their course schedules"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_analytics: ^12.0.1
  firebase_crashlytics: ^5.0.1
  
  # Authentication
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1
  
  # Excel processing
  excel: ^4.0.6
  file_picker: ^10.3.2
  
  # Calendar UI
  table_calendar: ^3.0.9
  syncfusion_flutter_calendar: ^31.1.17
  
  # State Management
  provider: ^6.1.1
  
  # Localization
  intl: ^0.20.2
  
  # UI/UX
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Local storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Notifications
  flutter_local_notifications: ^19.4.1
  
  # Calendar export
  add_2_calendar: ^3.0.1
  url_launcher: ^6.2.1
  pdf: ^3.10.7

  # Connectivity and offline support
  connectivity_plus: ^6.1.0

  # Additional utilities
  path_provider: ^2.1.1
  uuid: ^4.2.1
  http: ^1.1.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  generate: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    
  # Fonts (using default Material Design fonts for now)
  # TODO: Add custom fonts when available
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700