name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  # Explicitly disable Node.js detection
  NODE_VERSION: ''
  SKIP_INSTALL_SIMPLE_PROMPT: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Remove functions directory temporarily 
      run: |
        if [ -d "functions" ]; then
          mv functions functions_backup
        fi
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        cache: true
    
    - name: Verify Flutter installation
      run: |
        flutter doctor -v
        flutter config --no-analytics
    
    - name: Clean and get dependencies
      run: |
        flutter clean
        flutter pub get
    
    - name: Enable Flutter web
      run: flutter config --enable-web
    
    - name: Build Flutter web
      run: flutter build web --release --base-href "/ELTECalendar/" --web-renderer canvaskit --verbose
    
    - name: Verify build output
      run: |
        ls -la build/web/
        echo "Build completed successfully"
    
    - name: Add .nojekyll file (disable Jekyll processing)
      run: touch build/web/.nojekyll
    
    - name: Copy index.html to 404.html (for SPA routing)
      run: cp build/web/index.html build/web/404.html
    
    - name: Restore functions directory
      run: |
        if [ -d "functions_backup" ]; then
          mv functions_backup functions
        fi
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'build/web'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
